# custom_components/hahbt/services.yaml

log_habit:
  name: Log Habit
  description: Log an occurrence of a habit.
  fields:
    habit_id:
      description: The unique ID of the habit.
      example: "hbt-123456"
